version: '3.8'

services:
  app:
    depends_on:
      - mysqldb
    build: .
    env_file: .env
    restart: always
    container_name: movie-api
    ports: 
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$USERNAME
      - DB_PASSWORD=$PASSWORD
      - DB_NAME=$DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$PASSWORD
      - MYSQL_DATABASE=$DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

volumes: 
  db: