version: '3.9'

services:
  app:
    depends_on:
      - mysqldb
    build: .
    env_file: .env
    restart: always
    container_name: movie-api
    ports: 
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=${USERNAME}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}

  mysqldb:
    image: mysql:8
    restart: unless-stopped
    container_name: movies_api_db
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_USER=${USERNAME}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

volumes: 
  db: