name: Movie-Api-Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          DATABASE: ${{ secrets.DATABASE }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD:  ${{ secrets.PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # - name: Make envfile
      #   uses: SpicyPizza/create-envfile@v1
      #   with:
      #     envkey_DATABASE: ${{ secrets.DATABASE }}
      #     envkey_USERNAME: ${{ secrets.USERNAME }}
      #     envkey_HOST: ${{ secrets.HOST }}
      #     envkey_PASSWORD: ${{ secrets.PASSWORD }}
      #     envkey_MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      #     directory: "/home/runner/work/movies-api/movies-api/"

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - run: echo "${{ secrets.PROJECT_ENV}}" > .env

      - run: npm install

      - run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/movie_api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


